//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAPICodePack.Shell.Resources
{
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedMessages
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedMessages()
        {
        }

        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAPICodePack.Shell.Resources.LocalizedMessages", typeof(LocalizedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на AddToMostRecentlyUsedList cannot be changed while dialog is showing..
        /// </summary>
        internal static string AddToMostRecentlyUsedListCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("AddToMostRecentlyUsedListCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на AlwaysAppendDefaultExtension cannot be changed while dialog is showing..
        /// </summary>
        internal static string AlwaysAppendDefaultExtensionCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("AlwaysAppendDefaultExtensionCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Index was outside the bounds of the CommonFileDialogComboBox..
        /// </summary>
        internal static string ComboBoxIndexOutsideBounds
        {
            get
            {
                return ResourceManager.GetString("ComboBoxIndexOutsideBounds", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на File name not available - dialog was canceled..
        /// </summary>
        internal static string CommonFileDialogCanceled
        {
            get
            {
                return ResourceManager.GetString("CommonFileDialogCanceled", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Shell item could not be created..
        /// </summary>
        internal static string CommonFileDialogCannotCreateShellItem
        {
            get
            {
                return ResourceManager.GetString("CommonFileDialogCannotCreateShellItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Handle provided cannot be IntPtr.Zero..
        /// </summary>
        internal static string CommonFileDialogInvalidHandle
        {
            get
            {
                return ResourceManager.GetString("CommonFileDialogInvalidHandle", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Multiple files selected - the FileNames property should be used instead..
        /// </summary>
        internal static string CommonFileDialogMultipleFiles
        {
            get
            {
                return ResourceManager.GetString("CommonFileDialogMultipleFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Multiple files selected - the Items property should be used instead..
        /// </summary>
        internal static string CommonFileDialogMultipleItems
        {
            get
            {
                return ResourceManager.GetString("CommonFileDialogMultipleItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на File name not available - dialog has not closed yet..
        /// </summary>
        internal static string CommonFileDialogNotClosed
        {
            get
            {
                return ResourceManager.GetString("CommonFileDialogNotClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Common File Dialog requires Windows Vista or later..
        /// </summary>
        internal static string CommonFileDialogRequiresVista
        {
            get
            {
                return ResourceManager.GetString("CommonFileDialogRequiresVista", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Office Files.
        /// </summary>
        internal static string CommonFiltersOffice
        {
            get
            {
                return ResourceManager.GetString("CommonFiltersOffice", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на All Picture Files.
        /// </summary>
        internal static string CommonFiltersPicture
        {
            get
            {
                return ResourceManager.GetString("CommonFiltersPicture", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Text Files.
        /// </summary>
        internal static string CommonFiltersText
        {
            get
            {
                return ResourceManager.GetString("CommonFiltersText", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на CreatePrompt cannot be changed while dialog is showing..
        /// </summary>
        internal static string CreatePromptCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("CreatePromptCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom controls cannot be removed from a File dialog once added..
        /// </summary>
        internal static string DialogControlCollectionCannotRemoveControls
        {
            get
            {
                return ResourceManager.GetString("DialogControlCollectionCannotRemoveControls", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Control name cannot be null or zero length..
        /// </summary>
        internal static string DialogControlCollectionEmptyName
        {
            get
            {
                return ResourceManager.GetString("DialogControlCollectionEmptyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на CommonFileDialogMenuItem controls can only be added to CommonFileDialogMenu controls..
        /// </summary>
        internal static string DialogControlCollectionMenuItemControlsCannotBeAdded
        {
            get
            {
                return ResourceManager.GetString("DialogControlCollectionMenuItemControlsCannotBeAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Modifying controls collection while dialog is showing is not supported..
        /// </summary>
        internal static string DialogControlCollectionModifyingControls
        {
            get
            {
                return ResourceManager.GetString("DialogControlCollectionModifyingControls", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Dialog cannot have more than one control with the same name..
        /// </summary>
        internal static string DialogControlCollectionMoreThanOneControl
        {
            get
            {
                return ResourceManager.GetString("DialogControlCollectionMoreThanOneControl", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Dialog control must be removed from current collections first..
        /// </summary>
        internal static string DialogControlCollectionRemoveControlFirst
        {
            get
            {
                return ResourceManager.GetString("DialogControlCollectionRemoveControlFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на EnsureFileExists cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsureFileExistsCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("EnsureFileExistsCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на EnsurePathExists cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsurePathExistsCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("EnsurePathExistsCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на EnsureReadOnly cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsureReadonlyCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("EnsureReadonlyCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на EnsureValidNames cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsureValidNamesCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("EnsureValidNamesCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Browsing to object failed..
        /// </summary>
        internal static string ExplorerBrowserBrowseToObjectFailed
        {
            get
            {
                return ResourceManager.GetString("ExplorerBrowserBrowseToObjectFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на ExplorerBrowser failed to get current view..
        /// </summary>
        internal static string ExplorerBrowserFailedToGetView
        {
            get
            {
                return ResourceManager.GetString("ExplorerBrowserFailedToGetView", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get icon size..
        /// </summary>
        internal static string ExplorerBrowserIconSize
        {
            get
            {
                return ResourceManager.GetString("ExplorerBrowserIconSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Unexpected error retrieving item count..
        /// </summary>
        internal static string ExplorerBrowserItemCount
        {
            get
            {
                return ResourceManager.GetString("ExplorerBrowserItemCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Unexpected error retrieving selected item count..
        /// </summary>
        internal static string ExplorerBrowserSelectedItemCount
        {
            get
            {
                return ResourceManager.GetString("ExplorerBrowserSelectedItemCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Unexpected error retrieving selection..
        /// </summary>
        internal static string ExplorerBrowserUnexpectedError
        {
            get
            {
                return ResourceManager.GetString("ExplorerBrowserUnexpectedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Unexpected error retrieving view items..
        /// </summary>
        internal static string ExplorerBrowserViewItems
        {
            get
            {
                return ResourceManager.GetString("ExplorerBrowserViewItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The given path does not exist ({0}).
        /// </summary>
        internal static string FilePathNotExist
        {
            get
            {
                return ResourceManager.GetString("FilePathNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Guid does not identify a known folder..
        /// </summary>
        internal static string FolderIdsUnknownGuid
        {
            get
            {
                return ResourceManager.GetString("FolderIdsUnknownGuid", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на ControlPanel Category.
        /// </summary>
        internal static string FolderTypeCategory
        {
            get
            {
                return ResourceManager.GetString("FolderTypeCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на ControlPanel Classic.
        /// </summary>
        internal static string FolderTypeClassic
        {
            get
            {
                return ResourceManager.GetString("FolderTypeClassic", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Communications.
        /// </summary>
        internal static string FolderTypeCommunications
        {
            get
            {
                return ResourceManager.GetString("FolderTypeCommunications", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Compressed Folder.
        /// </summary>
        internal static string FolderTypeCompressedFolder
        {
            get
            {
                return ResourceManager.GetString("FolderTypeCompressedFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Contacts.
        /// </summary>
        internal static string FolderTypeContacts
        {
            get
            {
                return ResourceManager.GetString("FolderTypeContacts", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Documents.
        /// </summary>
        internal static string FolderTypeDocuments
        {
            get
            {
                return ResourceManager.GetString("FolderTypeDocuments", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Games.
        /// </summary>
        internal static string FolderTypeGames
        {
            get
            {
                return ResourceManager.GetString("FolderTypeGames", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Generic Library.
        /// </summary>
        internal static string FolderTypeGenericLibrary
        {
            get
            {
                return ResourceManager.GetString("FolderTypeGenericLibrary", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid.
        /// </summary>
        internal static string FolderTypeInvalid
        {
            get
            {
                return ResourceManager.GetString("FolderTypeInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Library.
        /// </summary>
        internal static string FolderTypeLibrary
        {
            get
            {
                return ResourceManager.GetString("FolderTypeLibrary", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Music.
        /// </summary>
        internal static string FolderTypeMusic
        {
            get
            {
                return ResourceManager.GetString("FolderTypeMusic", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Music Icons.
        /// </summary>
        internal static string FolderTypeMusicIcons
        {
            get
            {
                return ResourceManager.GetString("FolderTypeMusicIcons", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Network Explorer.
        /// </summary>
        internal static string FolderTypeNetworkExplorer
        {
            get
            {
                return ResourceManager.GetString("FolderTypeNetworkExplorer", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Not Specified.
        /// </summary>
        internal static string FolderTypeNotSpecified
        {
            get
            {
                return ResourceManager.GetString("FolderTypeNotSpecified", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Search.
        /// </summary>
        internal static string FolderTypeOpenSearch
        {
            get
            {
                return ResourceManager.GetString("FolderTypeOpenSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Other Users.
        /// </summary>
        internal static string FolderTypeOtherUsers
        {
            get
            {
                return ResourceManager.GetString("FolderTypeOtherUsers", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Pictures.
        /// </summary>
        internal static string FolderTypePictures
        {
            get
            {
                return ResourceManager.GetString("FolderTypePictures", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Printers.
        /// </summary>
        internal static string FolderTypePrinters
        {
            get
            {
                return ResourceManager.GetString("FolderTypePrinters", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на RecordedTV.
        /// </summary>
        internal static string FolderTypeRecordedTV
        {
            get
            {
                return ResourceManager.GetString("FolderTypeRecordedTV", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на RecycleBin.
        /// </summary>
        internal static string FolderTypeRecycleBin
        {
            get
            {
                return ResourceManager.GetString("FolderTypeRecycleBin", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved Games.
        /// </summary>
        internal static string FolderTypeSavedGames
        {
            get
            {
                return ResourceManager.GetString("FolderTypeSavedGames", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Search Connector.
        /// </summary>
        internal static string FolderTypeSearchConnector
        {
            get
            {
                return ResourceManager.GetString("FolderTypeSearchConnector", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Searches.
        /// </summary>
        internal static string FolderTypeSearches
        {
            get
            {
                return ResourceManager.GetString("FolderTypeSearches", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Generic SearchResults.
        /// </summary>
        internal static string FolderTypeSearchResults
        {
            get
            {
                return ResourceManager.GetString("FolderTypeSearchResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Software Explorer.
        /// </summary>
        internal static string FolderTypeSoftwareExplorer
        {
            get
            {
                return ResourceManager.GetString("FolderTypeSoftwareExplorer", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на User Files.
        /// </summary>
        internal static string FolderTypeUserFiles
        {
            get
            {
                return ResourceManager.GetString("FolderTypeUserFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Users Libraries.
        /// </summary>
        internal static string FolderTypeUserLibraries
        {
            get
            {
                return ResourceManager.GetString("FolderTypeUserLibraries", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Videos.
        /// </summary>
        internal static string FolderTypeVideos
        {
            get
            {
                return ResourceManager.GetString("FolderTypeVideos", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на IsExpandedMode cannot be changed while dialog is showing..
        /// </summary>
        internal static string IsExpandedModeCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("IsExpandedModeCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom categories cannot be added while recent documents tracking is turned off..
        /// </summary>
        internal static string JumpListCustomCategoriesDisabled
        {
            get
            {
                return ResourceManager.GetString("JumpListCustomCategoriesDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The file type is not registered with this application..
        /// </summary>
        internal static string JumpListFileTypeNotRegistered
        {
            get
            {
                return ResourceManager.GetString("JumpListFileTypeNotRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на JumpListLink&apos;s path is required and cannot be null..
        /// </summary>
        internal static string JumpListLinkPathRequired
        {
            get
            {
                return ResourceManager.GetString("JumpListLinkPathRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на JumpListLink&apos;s title is required and cannot be null..
        /// </summary>
        internal static string JumpListLinkTitleRequired
        {
            get
            {
                return ResourceManager.GetString("JumpListLinkTitleRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Negative numbers are not allowed for the ordinal position..
        /// </summary>
        internal static string JumpListNegativeOrdinalPosition
        {
            get
            {
                return ResourceManager.GetString("JumpListNegativeOrdinalPosition", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Given Known Folder ID is invalid..
        /// </summary>
        internal static string KnownFolderInvalidGuid
        {
            get
            {
                return ResourceManager.GetString("KnownFolderInvalidGuid", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Parsing name is invalid..
        /// </summary>
        internal static string KnownFolderParsingName
        {
            get
            {
                return ResourceManager.GetString("KnownFolderParsingName", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Creation of window has failed, view inner exception for details..
        /// </summary>
        internal static string MessageListenerCannotCreateWindow
        {
            get
            {
                return ResourceManager.GetString("MessageListenerCannotCreateWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Window class could not be registered, check inner exception for more details..
        /// </summary>
        internal static string MessageListenerClassNotRegistered
        {
            get
            {
                return ResourceManager.GetString("MessageListenerClassNotRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Message filter registration failed..
        /// </summary>
        internal static string MessageListenerFilterUnableToRegister
        {
            get
            {
                return ResourceManager.GetString("MessageListenerFilterUnableToRegister", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на No listener handled of that value is registered..
        /// </summary>
        internal static string MessageListenerFilterUnknownListenerHandle
        {
            get
            {
                return ResourceManager.GetString("MessageListenerFilterUnknownListenerHandle", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot create window on the listener thread because there is no existing window on the listener thread..
        /// </summary>
        internal static string MessageListenerNoWindowHandle
        {
            get
            {
                return ResourceManager.GetString("MessageListenerNoWindowHandle", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на NavigateToShortcut cannot be changed while dialog is showing..
        /// </summary>
        internal static string NavigateToShortcutCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("NavigateToShortcutCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Parent cannot be null..
        /// </summary>
        internal static string NavigationLogNullParent
        {
            get
            {
                return ResourceManager.GetString("NavigationLogNullParent", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The method or operation is not implemented..
        /// </summary>
        internal static string NotImplementedException
        {
            get
            {
                return ResourceManager.GetString("NotImplementedException", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на OverwritePrompt cannot be changed while dialog is showing..
        /// </summary>
        internal static string OverwritePromptCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("OverwritePromptCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на This CanonicalName is not a valid index..
        /// </summary>
        internal static string PropertyCollectionCanonicalInvalidIndex
        {
            get
            {
                return ResourceManager.GetString("PropertyCollectionCanonicalInvalidIndex", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на This PropertyKey is not a valid index..
        /// </summary>
        internal static string PropertyCollectionInvalidIndex
        {
            get
            {
                return ResourceManager.GetString("PropertyCollectionInvalidIndex", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument CanonicalName cannot be null or empty..
        /// </summary>
        internal static string PropertyCollectionNullCanonicalName
        {
            get
            {
                return ResourceManager.GetString("PropertyCollectionNullCanonicalName", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Index was outside the bounds of the CommonFileDialogRadioButtonList..
        /// </summary>
        internal static string RadioButtonListIndexOutOfBounds
        {
            get
            {
                return ResourceManager.GetString("RadioButtonListIndexOutOfBounds", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на RestoreDirectory cannot be changed while dialog is showing..
        /// </summary>
        internal static string RestoreDirectoryCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("RestoreDirectoryCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Retrieved a null shell item from dialog..
        /// </summary>
        internal static string SaveFileNullItem
        {
            get
            {
                return ResourceManager.GetString("SaveFileNullItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Given property key is invalid..
        /// </summary>
        internal static string SearchConditionFactoryInvalidProperty
        {
            get
            {
                return ResourceManager.GetString("SearchConditionFactoryInvalidProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Shell Exception has occurred, look at inner exception for information..
        /// </summary>
        internal static string ShellExceptionDefaultText
        {
            get
            {
                return ResourceManager.GetString("ShellExceptionDefaultText", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на GetParsingName has failed..
        /// </summary>
        internal static string ShellHelperGetParsingNameFailed
        {
            get
            {
                return ResourceManager.GetString("ShellHelperGetParsingNameFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The given CanonicalName is not valid..
        /// </summary>
        internal static string ShellInvalidCanonicalName
        {
            get
            {
                return ResourceManager.GetString("ShellInvalidCanonicalName", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на DefaultSaveFolder path not found..
        /// </summary>
        internal static string ShellLibraryDefaultSaveFolderNotFound
        {
            get
            {
                return ResourceManager.GetString("ShellLibraryDefaultSaveFolderNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на LibraryName cannot be empty..
        /// </summary>
        internal static string ShellLibraryEmptyName
        {
            get
            {
                return ResourceManager.GetString("ShellLibraryEmptyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder path not found..
        /// </summary>
        internal static string ShellLibraryFolderNotFound
        {
            get
            {
                return ResourceManager.GetString("ShellLibraryFolderNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid FolderType Guid..
        /// </summary>
        internal static string ShellLibraryInvalidFolderType
        {
            get
            {
                return ResourceManager.GetString("ShellLibraryInvalidFolderType", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The given known folder is not a valid library..
        /// </summary>
        internal static string ShellLibraryInvalidLibrary
        {
            get
            {
                return ResourceManager.GetString("ShellLibraryInvalidLibrary", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t get the display name..
        /// </summary>
        internal static string ShellObjectCannotGetDisplayName
        {
            get
            {
                return ResourceManager.GetString("ShellObjectCannotGetDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Destination array too small, or invalid arrayIndex..
        /// </summary>
        internal static string ShellObjectCollectionArrayTooSmall
        {
            get
            {
                return ResourceManager.GetString("ShellObjectCollectionArrayTooSmall", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Must have at least one shell object in the collection..
        /// </summary>
        internal static string ShellObjectCollectionEmptyCollection
        {
            get
            {
                return ResourceManager.GetString("ShellObjectCollectionEmptyCollection", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot insert items into a read only list..
        /// </summary>
        internal static string ShellObjectCollectionInsertReadOnly
        {
            get
            {
                return ResourceManager.GetString("ShellObjectCollectionInsertReadOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot remove items from a read only list..
        /// </summary>
        internal static string ShellObjectCollectionRemoveReadOnly
        {
            get
            {
                return ResourceManager.GetString("ShellObjectCollectionRemoveReadOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Shell item could not be created..
        /// </summary>
        internal static string ShellObjectCreationFailed
        {
            get
            {
                return ResourceManager.GetString("ShellObjectCreationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Shell Object creation requires Windows Vista or higher operating system..
        /// </summary>
        internal static string ShellObjectFactoryPlatformNotSupported
        {
            get
            {
                return ResourceManager.GetString("ShellObjectFactoryPlatformNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to Create Shell Item..
        /// </summary>
        internal static string ShellObjectFactoryUnableToCreateItem
        {
            get
            {
                return ResourceManager.GetString("ShellObjectFactoryUnableToCreateItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration for change notification has failed..
        /// </summary>
        internal static string ShellObjectWatcherRegisterFailed
        {
            get
            {
                return ResourceManager.GetString("ShellObjectWatcherRegisterFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to change watched events while listening..
        /// </summary>
        internal static string ShellObjectWatcherUnableToChangeEvents
        {
            get
            {
                return ResourceManager.GetString("ShellObjectWatcherUnableToChangeEvents", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The value on this property cannot be set. To set the property value, use the ShellObject that is associated with this property..
        /// </summary>
        internal static string ShellPropertyCannotSetProperty
        {
            get
            {
                return ResourceManager.GetString("ShellPropertyCannotSetProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на No constructor found matching requested argument types..
        /// </summary>
        internal static string ShellPropertyFactoryConstructorNotFound
        {
            get
            {
                return ResourceManager.GetString("ShellPropertyFactoryConstructorNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to set property..
        /// </summary>
        internal static string ShellPropertySetValue
        {
            get
            {
                return ResourceManager.GetString("ShellPropertySetValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get writable property store for this property..
        /// </summary>
        internal static string ShellPropertyUnableToGetWritableProperty
        {
            get
            {
                return ResourceManager.GetString("ShellPropertyUnableToGetWritableProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на A value had to be truncated in a string or rounded if a numeric value. Set AllowTruncatedValue to true to prevent this exception..
        /// </summary>
        internal static string ShellPropertyValueTruncated
        {
            get
            {
                return ResourceManager.GetString("ShellPropertyValueTruncated", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на This Property is available on Windows 7 only..
        /// </summary>
        internal static string ShellPropertyWindows7
        {
            get
            {
                return ResourceManager.GetString("ShellPropertyWindows7", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на This property only accepts a value of type \&quot;{0}\&quot;..
        /// </summary>
        internal static string ShellPropertyWrongType
        {
            get
            {
                return ResourceManager.GetString("ShellPropertyWrongType", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to set list of sort columns..
        /// </summary>
        internal static string ShellSearchFolderUnableToSetSortColumns
        {
            get
            {
                return ResourceManager.GetString("ShellSearchFolderUnableToSetSortColumns", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to set visible columns..
        /// </summary>
        internal static string ShellSearchFolderUnableToSetVisibleColumns
        {
            get
            {
                return ResourceManager.GetString("ShellSearchFolderUnableToSetVisibleColumns", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на CurrentSize (width or height) cannot be greater than the maximum size: {0}..
        /// </summary>
        internal static string ShellThumbnailCurrentSizeRange
        {
            get
            {
                return ResourceManager.GetString("ShellThumbnailCurrentSizeRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The current ShellObject does not have a thumbnail. Try using ShellThumbnailFormatOption.Default to get the icon for this item..
        /// </summary>
        internal static string ShellThumbnailDoesNotHaveThumbnail
        {
            get
            {
                return ResourceManager.GetString("ShellThumbnailDoesNotHaveThumbnail", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The current ShellObject does not have a valid thumbnail handler or there was a problem in extracting the thumbnail for this specific shell object..
        /// </summary>
        internal static string ShellThumbnailNoHandler
        {
            get
            {
                return ResourceManager.GetString("ShellThumbnailNoHandler", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на CurrentSize (width or height) cannot be 0..
        /// </summary>
        internal static string ShellThumbnailSizeCannotBe0
        {
            get
            {
                return ResourceManager.GetString("ShellThumbnailSizeCannotBe0", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на ShowHiddenItems cannot be changed while dialog is showing..
        /// </summary>
        internal static string ShowHiddenItemsCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("ShowHiddenItemsCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Show places list cannot be changed while dialog is showing..
        /// </summary>
        internal static string ShowPlacesListCannotBeChanged
        {
            get
            {
                return ResourceManager.GetString("ShowPlacesListCannotBeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The Stock Icon identifier given is invalid ({0})..
        /// </summary>
        internal static string StockIconInvalidGuid
        {
            get
            {
                return ResourceManager.GetString("StockIconInvalidGuid", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Child control&apos;s window handle cannot be zero..
        /// </summary>
        internal static string TabbedThumbnailZeroChildHandle
        {
            get
            {
                return ResourceManager.GetString("TabbedThumbnailZeroChildHandle", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Parent window handle cannot be zero..
        /// </summary>
        internal static string TabbedThumbnailZeroParentHandle
        {
            get
            {
                return ResourceManager.GetString("TabbedThumbnailZeroParentHandle", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на TabbedThumbnailProxyWindow has not been set..
        /// </summary>
        internal static string TasbarWindowProxyWindowSet
        {
            get
            {
                return ResourceManager.GetString("TasbarWindowProxyWindowSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на A valid active Window is needed to update the Taskbar..
        /// </summary>
        internal static string TaskbarManagerValidWindowRequired
        {
            get
            {
                return ResourceManager.GetString("TaskbarManagerValidWindowRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The array of buttons must contain at least 1 item..
        /// </summary>
        internal static string TaskbarWindowEmptyButtonArray
        {
            get
            {
                return ResourceManager.GetString("TaskbarWindowEmptyButtonArray", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Tool bar buttons for this window are already added. Please refer to the Remarks section of the AddButtons method for more information on updating the properties or hiding existing buttons..
        /// </summary>
        internal static string TaskbarWindowManagerButtonsAlreadyAdded
        {
            get
            {
                return ResourceManager.GetString("TaskbarWindowManagerButtonsAlreadyAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Value is already set. It cannot be set more than once..
        /// </summary>
        internal static string TaskbarWindowValueSet
        {
            get
            {
                return ResourceManager.GetString("TaskbarWindowValueSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The given control has not been added to the taskbar..
        /// </summary>
        internal static string ThumbnailManagerControlNotAdded
        {
            get
            {
                return ResourceManager.GetString("ThumbnailManagerControlNotAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Window handle is invalid..
        /// </summary>
        internal static string ThumbnailManagerInvalidHandle
        {
            get
            {
                return ResourceManager.GetString("ThumbnailManagerInvalidHandle", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на This preview has already been added..
        /// </summary>
        internal static string ThumbnailManagerPreviewAdded
        {
            get
            {
                return ResourceManager.GetString("ThumbnailManagerPreviewAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на The given preview has not been added to the taskbar..
        /// </summary>
        internal static string ThumbnailManagerPreviewNotAdded
        {
            get
            {
                return ResourceManager.GetString("ThumbnailManagerPreviewNotAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum number of buttons allowed is 7..
        /// </summary>
        internal static string ThumbnailToolbarManagerMaxButtons
        {
            get
            {
                return ResourceManager.GetString("ThumbnailToolbarManagerMaxButtons", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Null or empty arrays are not allowed..
        /// </summary>
        internal static string ThumbnailToolbarManagerNullEmptyArray
        {
            get
            {
                return ResourceManager.GetString("ThumbnailToolbarManagerNullEmptyArray", resourceCulture);
            }
        }
    }
}