//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NarodUploadWebClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NarodUploadWebClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap add_24 {
            get {
                object obj = ResourceManager.GetObject("add_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arc32 {
            get {
                object obj = ResourceManager.GetObject("arc32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arc32_2 {
            get {
                object obj = ResourceManager.GetObject("arc32_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arc64 {
            get {
                object obj = ResourceManager.GetObject("arc64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arc64_2 {
            get {
                object obj = ResourceManager.GetObject("arc64_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chfolder_24 {
            get {
                object obj = ResourceManager.GetObject("chfolder_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap date_24 {
            get {
                object obj = ResourceManager.GetObject("date_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete_24 {
            get {
                object obj = ResourceManager.GetObject("delete_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document32 {
            get {
                object obj = ResourceManager.GetObject("document32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document32_2 {
            get {
                object obj = ResourceManager.GetObject("document32_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document64 {
            get {
                object obj = ResourceManager.GetObject("document64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document64_2 {
            get {
                object obj = ResourceManager.GetObject("document64_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap faq_24 {
            get {
                object obj = ResourceManager.GetObject("faq_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  б..
        /// </summary>
        internal static string FilesProcess_Timer1Tick__b {
            get {
                return ResourceManager.GetString("FilesProcess_Timer1Tick__b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Кб/сек..
        /// </summary>
        internal static string FilesProcess_Timer1Tick__Kb_sek_ {
            get {
                return ResourceManager.GetString("FilesProcess_Timer1Tick__Kb_sek_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap folder32 {
            get {
                object obj = ResourceManager.GetObject("folder32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder32_2 {
            get {
                object obj = ResourceManager.GetObject("folder32_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder64 {
            get {
                object obj = ResourceManager.GetObject("folder64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder64_2 {
            get {
                object obj = ResourceManager.GetObject("folder64_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap idea_24 {
            get {
                object obj = ResourceManager.GetObject("idea_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap info_24 {
            get {
                object obj = ResourceManager.GetObject("info_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_24 {
            get {
                object obj = ResourceManager.GetObject("mail_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество файлов для загрузки: .
        /// </summary>
        internal static string MainForm_BUploadClick_Files_To_Upload__ {
            get {
                return ResourceManager.GetString("MainForm_BUploadClick_Files_To_Upload__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Распределять файлы по папкам после загрузки.
        /// </summary>
        internal static string MainForm_InitializeSettingForm_Files_To_Folder_After_Upload_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeSettingForm_Files_To_Folder_After_Upload_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Темы значков.
        /// </summary>
        internal static string MainForm_InitializeSettingForm_Icon_Themes_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeSettingForm_Icon_Themes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь:.
        /// </summary>
        internal static string MainForm_InitializeSettingForm_Login_ {
            get {
                return ResourceManager.GetString("MainForm_InitializeSettingForm_Login_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запоминать последнюю папку при выходе.
        /// </summary>
        internal static string MainForm_InitializeSettingForm_Memorize_last_folder_on_exit {
            get {
                return ResourceManager.GetString("MainForm_InitializeSettingForm_Memorize_last_folder_on_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прозрачность окна загрузки:.
        /// </summary>
        internal static string MainForm_InitializeSettingForm_Opacity_Uploading_Form__ {
            get {
                return ResourceManager.GetString("MainForm_InitializeSettingForm_Opacity_Uploading_Form__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль: .
        /// </summary>
        internal static string MainForm_InitializeSettingForm_Password__ {
            get {
                return ResourceManager.GetString("MainForm_InitializeSettingForm_Password__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображать окна загрузки в таскбаре.
        /// </summary>
        internal static string MainForm_InitializeSettingForm_Show_Uploading_Form_In_Taskbar {
            get {
                return ResourceManager.GetString("MainForm_InitializeSettingForm_Show_Uploading_Form_In_Taskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема 2.
        /// </summary>
        internal static string MainForm_InitializeSettingForm_Theme_2 {
            get {
                return ResourceManager.GetString("MainForm_InitializeSettingForm_Theme_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка.
        /// </summary>
        internal static string MainForm_InitializeSettingForm_Uploading {
            get {
                return ResourceManager.GetString("MainForm_InitializeSettingForm_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображение.
        /// </summary>
        internal static string MainForm_InitializeSettingForm_View__ {
            get {
                return ResourceManager.GetString("MainForm_InitializeSettingForm_View__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема 1.
        /// </summary>
        internal static string MainForm_InitializeSettingForm_Тheme_1 {
            get {
                return ResourceManager.GetString("MainForm_InitializeSettingForm_Тheme_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать.
        /// </summary>
        internal static string MainForm_Open__ {
            get {
                return ResourceManager.GetString("MainForm_Open__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор файла для загрузки на Яндекс.Диск.
        /// </summary>
        internal static string MainForm_OpenFileDialog_Caption__ {
            get {
                return ResourceManager.GetString("MainForm_OpenFileDialog_Caption__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все файлы (*.*)|*.*.
        /// </summary>
        internal static string MainForm_OpenFileDialog_Filter_All_Files__ {
            get {
                return ResourceManager.GetString("MainForm_OpenFileDialog_Filter_All_Files__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение успешно отправленно по адресу: .
        /// </summary>
        internal static string MainForm_SendLinks_Message_sended_ {
            get {
                return ResourceManager.GetString("MainForm_SendLinks_Message_sended_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основные.
        /// </summary>
        internal static string MainForm_Tabs_General__ {
            get {
                return ResourceManager.GetString("MainForm_Tabs_General__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string MainForm_Tabs_Settings__ {
            get {
                return ResourceManager.GetString("MainForm_Tabs_Settings__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОК.
        /// </summary>
        internal static string MainForm_tsFolder_Click_OK {
            get {
                return ResourceManager.GetString("MainForm_tsFolder_Click_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите папку.
        /// </summary>
        internal static string MainForm_tsFolder_Click_Select_folder {
            get {
                return ResourceManager.GetString("MainForm_tsFolder_Click_Select_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файлы:.
        /// </summary>
        internal static string MainForm_TsUploadClick_Files_ {
            get {
                return ResourceManager.GetString("MainForm_TsUploadClick_Files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        internal static string MainForm_Upload__ {
            get {
                return ResourceManager.GetString("MainForm_Upload__", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap music32 {
            get {
                object obj = ResourceManager.GetObject("music32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap music32_2 {
            get {
                object obj = ResourceManager.GetObject("music32_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap music64 {
            get {
                object obj = ResourceManager.GetObject("music64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap music64_2 {
            get {
                object obj = ResourceManager.GetObject("music64_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon pauseico {
            get {
                object obj = ResourceManager.GetObject("pauseico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picture32 {
            get {
                object obj = ResourceManager.GetObject("picture32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picture32_2 {
            get {
                object obj = ResourceManager.GetObject("picture32_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picture64 {
            get {
                object obj = ResourceManager.GetObject("picture64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picture64_2 {
            get {
                object obj = ResourceManager.GetObject("picture64_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pinned {
            get {
                object obj = ResourceManager.GetObject("pinned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon playico {
            get {
                object obj = ResourceManager.GetObject("playico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reload_24 {
            get {
                object obj = ResourceManager.GetObject("reload_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap root32 {
            get {
                object obj = ResourceManager.GetObject("root32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap root32_2 {
            get {
                object obj = ResourceManager.GetObject("root32_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap root64 {
            get {
                object obj = ResourceManager.GetObject("root64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap root64_2 {
            get {
                object obj = ResourceManager.GetObject("root64_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_24 {
            get {
                object obj = ResourceManager.GetObject("search_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap send_user_24 {
            get {
                object obj = ResourceManager.GetObject("send_user_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap setting_24 {
            get {
                object obj = ResourceManager.GetObject("setting_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap soft32 {
            get {
                object obj = ResourceManager.GetObject("soft32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap soft32_2 {
            get {
                object obj = ResourceManager.GetObject("soft32_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap soft64 {
            get {
                object obj = ResourceManager.GetObject("soft64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap soft64_2 {
            get {
                object obj = ResourceManager.GetObject("soft64_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unknown32 {
            get {
                object obj = ResourceManager.GetObject("unknown32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unknown32_2 {
            get {
                object obj = ResourceManager.GetObject("unknown32_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unknown64 {
            get {
                object obj = ResourceManager.GetObject("unknown64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unknown64_2 {
            get {
                object obj = ResourceManager.GetObject("unknown64_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unpinned {
            get {
                object obj = ResourceManager.GetObject("unpinned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Uploading {
            get {
                object obj = ResourceManager.GetObject("Uploading", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_24 {
            get {
                object obj = ResourceManager.GetObject("view_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
